server:
  port: 8081
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:file:./h2/winedb;
      username: soollan
      password: asdf12
  jpa:
    hibernate:
#      ddl-auto: create-drop #??
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect


resource:
  path: 'file:///Users/soollan/Downloads/'
upload:
  path: '/file/**'
